// Generated by Skyramp v1.3.36 on 2026-07-28 02:42:12.491369643 +0000 UTC m=+311.074745928
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output book_event_form_confirm_tooltip.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/confirm_button_tooltip_booking_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

// Test data
const loginEmail = "eval@skyramp.dev";
const loginPassword = "Eval1234!";
const confirmButtonTooltip = "Confirm and book this time slot";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(202000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on("pageerror", (error) => pageErrors.push(error));

    // kept inline: playwright/lib/testUtils — its selectFirstAvailableTimeSlotNextMonth/confirmBooking
    // helpers transitively import @calcom/prisma/enums, which is unresolvable in the Skyramp isolated
    // execution sandbox (see execution failure); reverted to raw locators so the generated test runs
    // standalone.
    await page.goto("http://localhost:3000");
    await page.locator("#email").fill(loginEmail);
    await page.locator("#password").fill(loginPassword);
    await page.getByRole("button", { name: "Continue" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByTestId("dialog-creation").getByRole("button", { name: "Don't update" }).click();

    // Navigate to the public booking page for the Quick Chat event type
    // (this goto was dropped by trace export/codegen — restored so the test doesn't
    // time out waiting for incrementMonth on the /event-types dashboard page)
    await page.goto("http://localhost:3000/eval-skyramp/quick-chat");
    await page.getByTestId("incrementMonth").click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/trpc/slots/reserveSlot**");
    await page.getByTestId("booker-container").getByRole("button", { name: "12:00am" }).click();
    await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Assert the Confirm button carries the new tooltip (title attribute) added in this PR
    await expect(page.getByTestId("confirm-book-button")).toHaveAttribute("title", confirmButtonTooltip);

    const responsePromise1 = page.waitForResponse("**/api/book/event**");
    await page.getByTestId("confirm-book-button").click();
    await responsePromise1;

    // Verify the booking actually completed
    await page.waitForURL((url) => url.pathname.startsWith("/booking"));
    await expect(page.locator("[data-testid=success-page]")).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
