// Generated by Skyramp v1.3.36 on 2026-07-24 18:26:06.785175537 +0000 UTC m=+366.558945022
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output event_types_new_button_tooltip.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/event_types_new_button_tooltip_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(506000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on("pageerror", (error) => pageErrors.push(error));

    await page.goto("http://localhost:3000/auth/login");
    await page.locator("#email").fill("eval@skyramp.dev");
    await page.locator("#password").fill("Eval1234!");
    await page.getByRole("button", { name: "Continue" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const timezoneDialogDismiss = page.getByTestId("dialog-creation").getByRole("button", { name: "Don't update" });
    if (await timezoneDialogDismiss.isVisible().catch(() => false)) {
        await timezoneDialogDismiss.click();
    }
    await page.goto("http://localhost:3000/event-types");
    await page.waitForSelector("text=New");
    // Timezone dialog is dismissed once per session (see "We won't show this again"); it may not reappear here.
    if (await timezoneDialogDismiss.isVisible().catch(() => false)) {
        await timezoneDialogDismiss.click();
    }
    await page.getByTestId("new-event-type").hover();
    await expect(page.getByTestId("new-event-type")).toContainText("New");
    await expect(page.getByTestId("new-event-type")).toHaveAttribute("title", "Create a new event type");
    expect(pageErrors).toHaveLength(0);
});
